
package com.insurance.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsuranaceImplService", targetNamespace = "http://service.insurance.com/", wsdlLocation = "http://localhost:4040/InsuranceWeb/findPlan?wsdl")
public class InsuranaceImplService
    extends Service
{

    private final static URL INSURANACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSURANACEIMPLSERVICE_EXCEPTION;
    private final static QName INSURANACEIMPLSERVICE_QNAME = new QName("http://service.insurance.com/", "InsuranaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4040/InsuranceWeb/findPlan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSURANACEIMPLSERVICE_WSDL_LOCATION = url;
        INSURANACEIMPLSERVICE_EXCEPTION = e;
    }

    public InsuranaceImplService() {
        super(__getWsdlLocation(), INSURANACEIMPLSERVICE_QNAME);
    }

    public InsuranaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSURANACEIMPLSERVICE_QNAME, features);
    }

    public InsuranaceImplService(URL wsdlLocation) {
        super(wsdlLocation, INSURANACEIMPLSERVICE_QNAME);
    }

    public InsuranaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSURANACEIMPLSERVICE_QNAME, features);
    }

    public InsuranaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsuranaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IInsurance
     */
    @WebEndpoint(name = "InsuranaceImplPort")
    public IInsurance getInsuranaceImplPort() {
        return super.getPort(new QName("http://service.insurance.com/", "InsuranaceImplPort"), IInsurance.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInsurance
     */
    @WebEndpoint(name = "InsuranaceImplPort")
    public IInsurance getInsuranaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.insurance.com/", "InsuranaceImplPort"), IInsurance.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSURANACEIMPLSERVICE_EXCEPTION!= null) {
            throw INSURANACEIMPLSERVICE_EXCEPTION;
        }
        return INSURANACEIMPLSERVICE_WSDL_LOCATION;
    }

}
