
package com.atm.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@HandlerChain(file="handler-chain.xml")
@WebServiceClient(name = "AtmImplService", targetNamespace = "http://service.atm.com/", wsdlLocation = "http://localhost:8086/AtmWeb/withdraw?wsdl")
public class AtmImplService
    extends Service
{

    private final static URL ATMIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATMIMPLSERVICE_EXCEPTION;
    private final static QName ATMIMPLSERVICE_QNAME = new QName("http://service.atm.com/", "AtmImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/AtmWeb/withdraw?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATMIMPLSERVICE_WSDL_LOCATION = url;
        ATMIMPLSERVICE_EXCEPTION = e;
    }

    public AtmImplService() {
        super(__getWsdlLocation(), ATMIMPLSERVICE_QNAME);
    }

    public AtmImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATMIMPLSERVICE_QNAME, features);
    }

    public AtmImplService(URL wsdlLocation) {
        super(wsdlLocation, ATMIMPLSERVICE_QNAME);
    }

    public AtmImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATMIMPLSERVICE_QNAME, features);
    }

    public AtmImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AtmImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAtm
     */
    @WebEndpoint(name = "AtmImplPort")
    public IAtm getAtmImplPort() {
        return super.getPort(new QName("http://service.atm.com/", "AtmImplPort"), IAtm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAtm
     */
    @WebEndpoint(name = "AtmImplPort")
    public IAtm getAtmImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.atm.com/", "AtmImplPort"), IAtm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATMIMPLSERVICE_EXCEPTION!= null) {
            throw ATMIMPLSERVICE_EXCEPTION;
        }
        return ATMIMPLSERVICE_WSDL_LOCATION;
    }

}
